version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ConnectionStrings__DefaultConnection=Host=database;Database=mydb;Username=postgres;Password=mypassword
      - ASPNETCORE_URLS=http://+:5000